# Generated by Django 6.1 on 2026-08-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password'),
        # Must run after the data copy, so accounts_subject rows are safely
        # duplicated into academics_subject before this table is dropped.
        ('academics', '0002_copy_subjects_from_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
