# Generated by Django 6.1 on 2026-08-30 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_copy_subjects_from_accounts'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('learning_mode', models.CharField(choices=[('IN_PERSON', 'In person'), ('ONLINE', 'Online')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=20)),
                ('withdrawn_at', models.DateField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='clients.student')),
                ('subjects', models.ManyToManyField(related_name='enrollments', to='academics.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
