# Generated by Django 6.1 on 2026-09-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_copy_subjects_from_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
