# Generated by Django 6.1 on 2026-09-26 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_seed_schools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='The Monday of the planned week.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academics.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='academics.topic')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week_start', 'subject__name'],
                'constraints': [models.UniqueConstraint(fields=('subject', 'week_start'), name='one_lesson_plan_per_subject_week')],
            },
        ),
    ]
