# Generated by Django 6.1 on 2026-08-30 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryStageChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, choices=[('INITIAL_CALL', 'Initial call'), ('MEETING_SET', 'Meeting set'), ('INVOICED', 'Invoiced'), ('ENROLLED', 'Enrolled')], max_length=20, null=True)),
                ('to_stage', models.CharField(choices=[('INITIAL_CALL', 'Initial call'), ('MEETING_SET', 'Meeting set'), ('INVOICED', 'Invoiced'), ('ENROLLED', 'Enrolled')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
                ('student_grade', models.CharField(max_length=20)),
                ('stage', models.CharField(choices=[('INITIAL_CALL', 'Initial call'), ('MEETING_SET', 'Meeting set'), ('INVOICED', 'Invoiced'), ('ENROLLED', 'Enrolled')], default='INITIAL_CALL', max_length=20)),
                ('duration_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('learning_mode', models.CharField(blank=True, choices=[('IN_PERSON', 'In person'), ('ONLINE', 'Online')], max_length=20, null=True)),
                ('desired_start_date', models.DateField(blank=True, null=True)),
                ('meeting_datetime', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
