# Generated by Django 6.1 on 2026-08-30 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_copy_subjects_from_accounts'),
        ('clients', '0001_initial'),
        ('enquiries', '0001_initial'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_enquiry', to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='interested_subjects',
            field=models.ManyToManyField(related_name='enquiries', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='clients.parent'),
        ),
        migrations.AddField(
            model_name='enquirystagechange',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_stage_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquirystagechange',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='enquiries.enquiry'),
        ),
    ]
