# Generated by Django 6.1 on 2026-09-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='student_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='student_school',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='student_year_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5'), (6, 'Year 6'), (7, 'Year 7'), (8, 'Year 8'), (9, 'Year 9'), (10, 'Year 10'), (11, 'Year 11'), (12, 'Year 12'), (13, 'Year 13')], null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='student_grade',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
