# Generated by Django 6.1 on 2026-09-04 16:54

from django.db import migrations, models


def copy_location_into_address(apps, schema_editor):
    """Best-effort data preservation for the location -> address/city split -
    existing free-text location values move into the new `address` field
    rather than being silently dropped. `city` is left blank since it can't
    be reliably parsed out of unstructured text."""
    Parent = apps.get_model('clients', 'Parent')
    Parent.objects.exclude(location='').update(address=models.F('location'))


def noop_reverse(apps, schema_editor):
    # No reverse data migration - reversing this migration already discards
    # the address/city columns via RemoveField, so there is nothing left to
    # copy back into `location`.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parent',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(copy_location_into_address, noop_reverse),
        migrations.RemoveField(
            model_name='parent',
            name='location',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='year_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5'), (6, 'Year 6'), (7, 'Year 7'), (8, 'Year 8'), (9, 'Year 9'), (10, 'Year 10'), (11, 'Year 11'), (12, 'Year 12'), (13, 'Year 13')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
